INSERT INTO MODEL1 VALUES (1, 'Ramesh','A'); 
INSERT INTO MODEL1 VALUES (2, 'Ramesh1','A'); 
INSERT INTO MODEL1 VALUES (3, 'Ramesh4','A2'); 
INSERT INTO MODEL1 VALUES (4, 'Ramesh4','A4'); 
INSERT INTO MODEL1 VALUES (5, 'Ramesh4','A2'); 